" syntax highlighting
syntax on
colorscheme boring

" indentation
set tabstop=2
set shiftwidth=2
set expandtab

" center cursor vertically
set scrolloff=25

" disable swapfile
set noswapfile

" set leader to <space>
let mapleader=" "

" switch between windows and tabs
nnoremap <leader><Tab> g<Tab>
nnoremap <leader>w <C-w><C-w>

" enter command mode
noremap <leader>; :
" search replace inner word or visual selection
nnoremap <leader>/ yiw:%s/<C-r>"/<C-r>"
vnoremap <leader>/ y:%s/<C-r>"/<C-r>"

" resize vertical splits
map <leader>= :exe "vertical resize +10"<CR>
map <leader>- :exe "vertical resize -10"<CR>

" disable yank when pasting in visual mode
vnoremap p "_dP

" FZF
set rtp+=~/.vim/pack/plugins/start/fzf
:noremap <c-p> :FZF<CR>
